// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_level_2_passed = "CgkI8erA-qUcEAIQBA"; // <GPGSID>
        public const string achievement_level_1_passed = "CgkI8erA-qUcEAIQAw"; // <GPGSID>
        public const string achievement_level_3_passed = "CgkI8erA-qUcEAIQBQ"; // <GPGSID>
        public const string leaderboard_level_3_score = "CgkI8erA-qUcEAIQCg"; // <GPGSID>
        public const string leaderboard_level_2_score = "CgkI8erA-qUcEAIQCQ"; // <GPGSID>
        public const string leaderboard_level_5_score = "CgkI8erA-qUcEAIQDA"; // <GPGSID>
        public const string achievement_level_4_passed = "CgkI8erA-qUcEAIQBg"; // <GPGSID>
        public const string leaderboard_level_4_score = "CgkI8erA-qUcEAIQCw"; // <GPGSID>
        public const string leaderboard_level_1_score = "CgkI8erA-qUcEAIQAg"; // <GPGSID>
        public const string achievement_level_5_passed = "CgkI8erA-qUcEAIQBw"; // <GPGSID>
        public const string achievement_demolisher_of_blocks = "CgkI8erA-qUcEAIQCA"; // <GPGSID>

}

